spring:
  application:
    name: portal-aluno
    profiles:
      active:
        - dev

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    display-request-duration: true
    doc-expansion: none
    groups-order: DESC
    operationsSorter: alpha
    tagsSorter: alpha
    path: /swagger-ui.html
    title: Portal Aluno

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
