spring:
  datasource:
    url: jdbc:postgresql://portal-aluno.czykd9frqmhb.sa-east-1.rds.amazonaws.com:5432/portal_aluno
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 50
        show_sql: false
        format_sql: true
    show-sql: false
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    display-request-duration: true
    doc-expansion: none
    groups-order: DESC
    operationsSorter: alpha
    tagsSorter: alpha
    path: /swagger-ui.html
    title: Portal Aluno

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
