name: Deploy em prod
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build project
        run: mvn clean install

      - name: Build and analyze
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=joaoeffs_portal-aluno-java  
            -Dsonar.organization=joaoeffs  
            -Dsonar.host.url=https://sonarcloud.io 
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login docker hub
        run: docker login -u ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}

      - name: Builder docker image
        run: docker build -t joaoeffs/portal-aluno .

      - name: Push image docker
        run: docker push joaoeffs/portal-aluno

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull joaoeffs/portal-aluno:latest

      - name: Remover docker container
        run: docker rm -f portal-aluno-container

      - name: Run docker container
        run: |
            docker run -d -p 8080:8080 \
                -e DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
                -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
                -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
                --name portal-aluno-container joaoeffs/portal-aluno
